<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">

  <link rel="stylesheet" href="<?= \The\asset_url('/css/app.css') ?>">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>

  <title>Pickem</title>
</head>
<body>

<div>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" data-topbar data-options="is_hover: false">

      <a class="navbar-brand mb-0 h1" href="/">Pickem</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="/app/#/football/my-picks" class="nav-link">My Picks</a>
          </li>
          <li class="nav-item">
            <a href="/app/#/football/league-picks" class="nav-link">League Picks</a>
          </li>
          <li class="nav-item">
            <a href="/app/#/football/fantasy-standings" class="nav-link">Fantasy Standings</a>
          </li>
          <li class="nav-item">
            <a href="/app/#/football/schedule" class="nav-link">Schedule</a>
          </li>
          <li class="nav-item">
            <a href="/app/#/football/team-standings" class="nav-link">Team Standings</a>
          </li>

        </ul>

        <ul class="navbar-nav my-2 my-lg-0 ml-auto">
          <?php if (!empty($this['user'])): ?>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hello <?= $this['user']['username'] ?>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a href="/app/#/user/profile" class="dropdown-item">Edit Profile</a>
                <a href="/app/#/user/password" class="dropdown-item">Change Password</a>
                <a href="/app/#/user/logout" class="dropdown-item">Logout</a>
              </div>
            </li>
          <?php else: ?>
            <li lds-authenticated="false" class="nav-item"><a href="/app/#/user/login" class="nav-link">Login</a>
          </li>
          <?php endif ?>
        </ul>

      </div>

    </nav>
  </header>

</div>

<?php include $view_file ?>

</body>
</html>
