version: '3.7'
services:
  nginx:
    image: nginx:1.17.3-alpine
    restart: always
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      default:
      reverse-proxy:
        aliases:
          - pickem
          - pickem.frontend
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/app
      - ~/.composer:/root/.composer
    working_dir: /app
    environment:
      - APP_ENV
      - DATABASE_URL

  mariadb:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./bin:/app/bin
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - DROPBOX_TOKEN
      - HONEYBADGER_MARIA_BACKUPS_CHECKIN

networks:
  reverse-proxy:
    external:
      name: "${REVERSE_PROXY_NETWORK:-frontend}"
