<html ng-app="app">
    <head>
        <title>Lightdatasys</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $app['lstr.asset']->cssTag('app/bundle/application.css'); ?>
    </head>
    <body ng-controller="AppCtrl">

        <div style="display: none; " ng-style="{'display': 'block'}">

            <nav class="top-bar" data-topbar data-options="is_hover: false">
                <ul class="title-area">
                    <li class="toggle-topbar menu-icon">
                        <a href="#">Menu</a>
                    </li>
                    <li class="name">
                        <h1><a href="#/">Lightdatasys</a></h1>
                    </li>
                </ul>

                <ul class="">
                </ul>

                <section class="top-bar-section">
                    <!-- Right Nav Section -->
                    <ul class="right">
                        <li lds-authenticated="true" lds-user-info class="has-dropdown">
                            <a href="#" class="dropdown-parent">
                                Hello {{user.username}}
                            </a>
                            <ul class="dropdown">
                                <li><a href="#/user/profile">Edit Profile</a></li>
                                <li><a href="#/user/password">Change Password</a></li>
                            </ul>
                        </li>
                        <li lds-authenticated="false"><a href="#/user/login">Login</a></li>
                        <li lds-authenticated="true"><a href="#/user/logout">Logout</a></li>
                    </ul>

                    <!-- Left Nav Section -->
                    <ul class="left">
                        <li><a href="#/football/my-picks">Football</a></lI>
                    </ul>
                </section>
            </nav>

            <ng-view>
                Loading
            </ng-view>

            <?php echo $app['lstr.asset']->jsTag('app/bundle/application.js'); ?>

        </div>

        <div class="row" ng-style="{'display': 'none'}">
            <div class="alert-box secondary small-10 small-offset-1 columns text-center radius" style="margin-top: 10px; ">
                Loading...
            </div>
        </div>

    </body>
</html>
