<html ng-app="app">
    <head>
        <title>Lightdatasys</title>

        <?php echo $app['lstr.asset']->cssTag('app/bundle/application.css'); ?>
    </head>
    <body ng-controller="AppCtrl">

        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="toggle-topbar menu-icon">
                    <a href="#">Menu</a>
                </li>
                <li class="name">
                    <h1><a href="#/">Lightdatasys</a></h1>
                </li>
            </ul>

            <ul class="">
            </ul>

            <section class="top-bar-section">
                <!-- Right Nav Section -->
                <ul class="right" lds-authenticated="false">
                    <li><a href="#/user/login">Login</a></li>
                </ul>

                <!-- Left Nav Section -->
                <ul class="left">
                    <li><a href="#/football/schedule">Football</a></lI>
                </ul>
            </section>
        </nav>

        <ng-view>
            Loading
        </ng-view>

        <?php echo $app['lstr.asset']->jsTag('app/bundle/application.js'); ?>

    </body>
</html>