<div class="row">
		<div class="span4">
				<h2><?php echo $this->translate('Football Pick\'em') ?></h2>
				<p><?php echo sprintf($this->translate('The Commissioner is going to win, but you still have a chance at second place. Be sure to %scheck the standings%s and never forget to'), '<a href="' . $this->url('home') . '">', '</a>') ?>...</p>
				<p><a class="btn btn-info" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Make your picks') ?> &raquo;</a></p>
		</div>

		<div class="span4">
				<h2><?php echo $this->translate('Race\'m') ?></h2>
				<p><?php echo sprintf($this->translate('... or wreck\'m! Who do you think is going to finish near the front?')) ?></p>
				<p><a class="btn btn-info" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Set your starting grid') ?> &raquo;</a></p>
		</div>
</div>